import { mkdtemp, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { test } from 'node:test';
import assert from 'node:assert/strict';

import {
  BACKEND_IMAGE_MODEL,
  CODEX_IMAGE_GEN_PROVIDER,
  CODEX_IMAGE_GEN_TOOL_NAME,
} from '../src/constants.ts';
import {
  CODEX_IMAGE_GEN_HELP_COMMAND_NAME,
  CODEX_IMAGE_GEN_HELP_TEXT,
  CODEX_IMAGE_GEN_TOOL_LABEL,
  createCodexImageGenToolDefinition,
  registerCodexImageGenTool,
} from '../src/pi/registerCodexImageGenTool.ts';

const imageBase64 = Buffer.from('fake pi execution image bytes').toString('base64');

function fakeJwt(claims) {
  const header = Buffer.from(JSON.stringify({ alg: 'none', typ: 'JWT' })).toString('base64url');
  const payload = Buffer.from(JSON.stringify(claims)).toString('base64url');
  const signature = Buffer.from('signature').toString('base64url');
  return `${header}.${payload}.${signature}`;
}

function fakeCodexToken() {
  return fakeJwt({
    sub: 'user_pi_registration_test',
    exp: 4_102_444_800,
    'https://api.openai.com/auth': {
      chatgpt_account_id: 'acct_pi_registration_test',
      chatgpt_user_id: 'chatgpt_user_pi_registration_test',
      chatgpt_plan_type: 'plus',
    },
  });
}

async function withTempRoot(fn) {
  const root = await mkdtemp(join(tmpdir(), 'pi-codex-image-gen-pi-'));
  try {
    await fn({
      root,
      cwd: join(root, 'project'),
      agentDir: join(root, 'agent'),
    });
  } finally {
    await rm(root, { recursive: true, force: true });
  }
}

function createFakeContext({ cwd, agentDir, token = fakeCodexToken(), sessionId = 'sess_pi_registration' }) {
  const requestedProviders = [];
  return {
    ctx: {
      cwd,
      agentDir,
      modelRegistry: {
        async getApiKeyForProvider(provider) {
          requestedProviders.push(provider);
          return token;
        },
      },
      sessionManager: {
        getSessionId() {
          return sessionId;
        },
      },
    },
    requestedProviders,
  };
}

test('registers the Pi tool metadata and optional help command', async () => {
  const registeredTools = [];
  const registeredCommands = [];
  const sentMessages = [];
  const pi = {
    registerTool(tool) {
      registeredTools.push(tool);
    },
    registerCommand(name, definition) {
      registeredCommands.push({ name, definition });
    },
    sendMessage(message, options) {
      sentMessages.push({ message, options });
    },
  };

  registerCodexImageGenTool(pi, {
    client: {
      async generateImage() {
        throw new Error('client should not run during registration');
      },
    },
  });

  assert.equal(registeredTools.length, 1);
  const [tool] = registeredTools;
  assert.equal(tool.name, CODEX_IMAGE_GEN_TOOL_NAME);
  assert.equal(tool.label, CODEX_IMAGE_GEN_TOOL_LABEL);
  assert.match(tool.description, /openai-codex/);
  assert.equal(tool.executionMode, 'sequential');
  assert.ok(tool.promptSnippet.includes('Generate bitmap images'));
  assert.ok(tool.promptGuidelines.some((guideline) => guideline.includes('explicit image-generation')));
  assert.deepEqual(tool.parameters.required, ['prompt']);

  assert.equal(registeredCommands.length, 1);
  assert.equal(registeredCommands[0].name, CODEX_IMAGE_GEN_HELP_COMMAND_NAME);
  const notifications = [];
  let waited = false;
  await registeredCommands[0].definition.handler('', {
    ...createFakeContext({ cwd: process.cwd(), agentDir: '/tmp/pi-agent' }).ctx,
    hasUI: true,
    ui: {
      notify(message, type) {
        notifications.push({ message, type });
      },
    },
    async waitForIdle() {
      waited = true;
    },
  });

  assert.equal(waited, true);
  assert.equal(sentMessages.length, 0);
  assert.equal(notifications.length, 1);
  assert.equal(notifications[0].type, 'info');
  assert.equal(notifications[0].message, CODEX_IMAGE_GEN_HELP_TEXT);
});

test('registered tool execution wires config, auth, client, save, and output modules', async () => {
  await withTempRoot(async ({ cwd, agentDir }) => {
    const clientCalls = [];
    const configLoadCalls = [];
    const client = {
      async generateImage(input, auth, options) {
        clientCalls.push({ input, auth, options });
        return {
          provider: CODEX_IMAGE_GEN_PROVIDER,
          routingModel: input.model,
          backendImageModel: BACKEND_IMAGE_MODEL,
          outputFormat: input.outputFormat,
          base64Image: imageBase64,
          text: 'Generated by fake client.',
          responseId: 'resp_pi_registration',
          imageGenerationId: 'ig_pi_registration',
          revisedPrompt: 'A concise fake test icon.',
          usage: { input_tokens: 4, output_tokens: 5, total_tokens: 9 },
        };
      },
    };
    const tool = createCodexImageGenToolDefinition({
      client,
      async loadConfig(options) {
        configLoadCalls.push(options);
        return {
          config: { model: 'gpt-test-routing', saveMode: 'none' },
          paths: {
            globalPath: join(agentDir, 'extensions', 'codex-image-gen.json'),
            projectPath: join(cwd, '.pi', 'extensions', 'codex-image-gen.json'),
          },
          loadedFiles: [],
        };
      },
    });
    const { ctx, requestedProviders } = createFakeContext({ cwd, agentDir });
    const updates = [];

    const result = await tool.execute(
      'tool-call-pi-registration',
      { prompt: '  flat blue circle test icon, no text  ', outputFormat: 'webp' },
      undefined,
      (update) => updates.push(update),
      ctx,
    );

    assert.equal(configLoadCalls.length, 1);
    assert.equal(configLoadCalls[0].cwd, cwd);
    assert.equal(configLoadCalls[0].agentDir, agentDir);
    assert.equal(requestedProviders.length, 1);
    assert.equal(requestedProviders[0], CODEX_IMAGE_GEN_PROVIDER);

    assert.equal(clientCalls.length, 1);
    assert.deepEqual(clientCalls[0].input, {
      prompt: 'flat blue circle test icon, no text',
      model: 'gpt-test-routing',
      outputFormat: 'webp',
      save: 'none',
    });
    assert.equal(clientCalls[0].auth.provider, CODEX_IMAGE_GEN_PROVIDER);
    assert.equal(clientCalls[0].auth.accountId, 'acct_pi_registration_test');
    assert.equal(clientCalls[0].options.sessionId, 'sess_pi_registration');
    assert.equal(clientCalls[0].options.threadId, 'tool-call-pi-registration');

    assert.equal(updates.length, 1);
    assert.match(updates[0].content[0].text, /Generating image via openai-codex\/gpt-test-routing/);
    assert.equal(updates[0].details.outputFormat, 'webp');

    assert.equal(result.content.length, 2);
    assert.equal(result.content[0].type, 'text');
    assert.match(result.content[0].text, /no image file was written/);
    assert.deepEqual(result.content[1], {
      type: 'image',
      data: imageBase64,
      mimeType: 'image/webp',
    });
    assert.deepEqual(result.details, {
      provider: CODEX_IMAGE_GEN_PROVIDER,
      routingModel: 'gpt-test-routing',
      backendImageModel: BACKEND_IMAGE_MODEL,
      outputFormat: 'webp',
      saveMode: 'none',
      responseId: 'resp_pi_registration',
      imageGenerationId: 'ig_pi_registration',
      revisedPrompt: 'A concise fake test icon.',
      usage: { input_tokens: 4, output_tokens: 5, total_tokens: 9 },
    });
  });
});
